import{expect,test,type Page}from'@playwright/test';
const queuePath='/src/services/safeWork/localQueue.ts',flowPath='/src/services/academic/rapidCorrection.ts';
async function clear(page:Page){await page.evaluate(async p=>{const m=await import(p);await m.safeWorkDb.operations.clear();localStorage.removeItem('golden40-supabase');indexedDB.deleteDatabase('golden-40-workflow');},queuePath)}
test.beforeEach(async({page})=>{await page.goto('/');await clear(page)});

test('Golden 40 follows arbitrary paper workflow and resumes the persisted CorrectionSession',async({page})=>{
  const beforeReload=await page.evaluate(async({qpath,fpath})=>{
    const q=await import(qpath),flow=await import(fpath);
    const storageKey='golden40-supabase';
    const makeClient=()=>({from(table:string){
      let filters:[string,unknown][]=[],orderBy:null|{key:string;ascending:boolean}=null,limitN:number|null=null,mutation:null|{kind:'insert';row:any}|{kind:'update';patch:any}=null;
      const read=()=>JSON.parse(localStorage.getItem(storageKey)||'{}') as Record<string,any[]>;
      const write=(db:Record<string,any[]>)=>localStorage.setItem(storageKey,JSON.stringify(db));
      const matches=(row:any)=>filters.every(([k,v])=>row[k]===v);
      const execute=()=>{const db=read();db[table]??=[];if(mutation?.kind==='insert'){const now=new Date().toISOString(),row={...mutation.row};if(table==='correction_sessions'){row.started_at??=now;row.updated_at??=now;row.completed_at??=null;}db[table].push(row);write(db);return[row];}if(mutation?.kind==='update'){const patch=(mutation as{kind:'update';patch:any}).patch,changed:any[]=[];db[table]=db[table].map(row=>{if(!matches(row))return row;const next={...row,...patch};changed.push(next);return next;});write(db);return changed;}let rows=db[table].filter(matches);if(orderBy)rows=[...rows].sort((a,b)=>{const c=String(a[orderBy!.key]??'').localeCompare(String(b[orderBy!.key]??''));return orderBy!.ascending?c:-c;});if(limitN!==null)rows=rows.slice(0,limitN);return rows;};
      const builder:any={select(){return builder;},eq(k:string,v:unknown){filters.push([k,v]);return builder;},order(k:string,o:{ascending:boolean}){orderBy={key:k,ascending:o.ascending};return builder;},limit(n:number){limitN=n;return builder;},insert(row:any){mutation={kind:'insert',row};return builder;},update(patch:any){mutation={kind:'update',patch};return builder;},async single(){const rows=execute();return rows.length===1?{data:rows[0],error:null}:{data:null,error:new Error(`Expected one ${table} row, got ${rows.length}`)};},async maybeSingle(){const rows=execute();return rows.length<=1?{data:rows[0]??null,error:null}:{data:null,error:new Error(`Expected <=1 ${table} row`)};},then(resolve:any,reject:any){return Promise.resolve({data:execute(),error:null}).then(resolve,reject);}};return builder;
    }}) as any;
    const students=Array.from({length:40},(_,i)=>({id:`s${i}`,workspace_id:'w',display_name:i===3||i===27?'Nama Sama':`Siswa ${i+1}`,nis:String(1000+i),nisn:null,revision:0,created_at:'',updated_at:''}));
    const enrollments=students.map((s,i)=>({id:`e${i}`,workspace_id:'w',class_id:'c',student_id:s.id,status:'active',created_at:'',updated_at:''}));
    localStorage.setItem(storageKey,JSON.stringify({assessments:[{id:'a',workspace_id:'w',class_id:'c',academic_period_id:'p',activity_id:null,scoring_profile_id:null,title:'UH',description:null,instructions:null,status:'active',created_at:'',updated_at:''}],classes:[{id:'c',workspace_id:'w',academic_period_id:'p',display_name:'VIII A',created_at:'',updated_at:''}],students,enrollments,assessment_results:[],scoring_profiles:[],correction_sessions:[]}));
    const client=makeClient(),db=new q.SafeWorkDb('golden-40-workflow');await db.operations.clear();
    let context=await flow.loadCorrectionContext(client,'w','a');
    const duplicate=flow.searchCorrectionStudents(context,'Nama Sama').map((x:any)=>[x.student.display_name,x.student.nis,x.enrollment.id]);
    let session=await flow.startOrResumeCorrection(client,'w',context.assessment,context.session);
    const startedId=session.id,order=[...Array(40).keys()].sort((a,b)=>(a*17)%41-(b*17)%41),handled:any[]=[];
    for(let n=0;n<20;n++){const i=order[n],found=flow.searchCorrectionStudents(context,students[i].nis)[0];if(!found||found.enrollment.id!==`e${i}`)throw new Error('search lost paper owner');session=await flow.setCorrectionPosition(client,session,found.enrollment.id);let state:any='GRADED',score:any=i+1;if(n===1)score=0;if(n===2)score=-5;if(n===3)state='UNCHECKED';if(n===4)state='MISSING';if(n===5)state='EXCUSED';if(state==='UNCHECKED'){handled.push([i,'SKIP',null]);continue;}await flow.queueCorrectionJudgement(db,{authUserId:'u',workspaceId:'w',assessmentId:'a',enrollmentId:found.enrollment.id,state,score:state==='GRADED'?score:null,result:null});handled.push([i,state,state==='GRADED'?score:null]);}
    const pending=await q.pendingForNamespace(db,'u','w'),persisted=await flow.loadCorrectionContext(client,'w','a'),raw=JSON.parse(localStorage.getItem(storageKey)||'{}');db.close();
    return{startedId,status:session.status,position:session.current_enrollment_id,persistedId:persisted.session?.id,persistedStatus:persisted.session?.status,persistedPosition:persisted.session?.current_enrollment_id,pendingCount:pending.length,sessionCount:raw.correction_sessions.length,duplicate,order,handled};
  },{qpath:queuePath,fpath:flowPath});
  expect(beforeReload.persistedId).toBe(beforeReload.startedId);expect(beforeReload.status).toBe('active');expect(beforeReload.persistedStatus).toBe('active');expect(beforeReload.persistedPosition).toBe(beforeReload.position);expect(beforeReload.sessionCount).toBe(1);expect(beforeReload.pendingCount).toBe(19);expect(beforeReload.duplicate).toEqual([['Nama Sama','1003','e3'],['Nama Sama','1027','e27']]);

  await page.reload();

  const afterReload=await page.evaluate(async({qpath,fpath,startedId,order})=>{
    const q=await import(qpath),flow=await import(fpath),storageKey='golden40-supabase';
    const makeClient=()=>({from(table:string){let filters:[string,unknown][]=[],orderBy:null|{key:string;ascending:boolean}=null,limitN:number|null=null,mutation:null|{kind:'insert';row:any}|{kind:'update';patch:any}=null;const read=()=>JSON.parse(localStorage.getItem(storageKey)||'{}') as Record<string,any[]>;const write=(db:Record<string,any[]>)=>localStorage.setItem(storageKey,JSON.stringify(db));const matches=(row:any)=>filters.every(([k,v])=>row[k]===v);const execute=()=>{const db=read();db[table]??=[];if(mutation?.kind==='insert'){const now=new Date().toISOString(),row={...mutation.row};if(table==='correction_sessions'){row.started_at??=now;row.updated_at??=now;row.completed_at??=null;}db[table].push(row);write(db);return[row];}if(mutation?.kind==='update'){const patch=(mutation as{kind:'update';patch:any}).patch,changed:any[]=[];db[table]=db[table].map(row=>{if(!matches(row))return row;const next={...row,...patch};changed.push(next);return next;});write(db);return changed;}let rows=db[table].filter(matches);if(orderBy)rows=[...rows].sort((a,b)=>{const c=String(a[orderBy!.key]??'').localeCompare(String(b[orderBy!.key]??''));return orderBy!.ascending?c:-c;});if(limitN!==null)rows=rows.slice(0,limitN);return rows;};const builder:any={select(){return builder;},eq(k:string,v:unknown){filters.push([k,v]);return builder;},order(k:string,o:{ascending:boolean}){orderBy={key:k,ascending:o.ascending};return builder;},limit(n:number){limitN=n;return builder;},insert(row:any){mutation={kind:'insert',row};return builder;},update(patch:any){mutation={kind:'update',patch};return builder;},async single(){const rows=execute();return rows.length===1?{data:rows[0],error:null}:{data:null,error:new Error(`Expected one ${table} row, got ${rows.length}`)};},async maybeSingle(){const rows=execute();return rows.length<=1?{data:rows[0]??null,error:null}:{data:null,error:new Error(`Expected <=1 ${table} row`)};},then(resolve:any,reject:any){return Promise.resolve({data:execute(),error:null}).then(resolve,reject);}};return builder;}}) as any;
    const client=makeClient(),db=new q.SafeWorkDb('golden-40-workflow');
    let context=await flow.loadCorrectionContext(client,'w','a');if(!context.session)throw new Error('active CorrectionSession was not recovered');const recoveredBeforeResume={id:context.session.id,status:context.session.status,position:context.session.current_enrollment_id};
    let session=await flow.startOrResumeCorrection(client,'w',context.assessment,context.session);const rawAfterResume=JSON.parse(localStorage.getItem(storageKey)||'{}'),students=context.students;
    for(let n=20;n<40;n++){const i=order[n],found=flow.searchCorrectionStudents(context,students.find((s:any)=>s.id===`s${i}`)?.nis??'')[0];if(!found||found.enrollment.id!==`e${i}`)throw new Error('search lost paper owner after resume');session=await flow.setCorrectionPosition(client,session,found.enrollment.id);const state:any='GRADED',score:any=i+1;await flow.queueCorrectionJudgement(db,{authUserId:'u',workspaceId:'w',assessmentId:'a',enrollmentId:found.enrollment.id,state,score,result:null});}
    const beforeComplete=await flow.loadCorrectionContext(client,'w','a');if(!beforeComplete.session)throw new Error('session disappeared before completion');const completed=await flow.completeCorrection(client,beforeComplete.session);const reread=await flow.loadCorrectionContext(client,'w','a'),pending=await q.pendingForNamespace(db,'u','w'),rawFinal=JSON.parse(localStorage.getItem(storageKey)||'{}');db.close();
    return{startedId,recoveredBeforeResume,resumedId:session.id,resumeSessionCount:rawAfterResume.correction_sessions.length,resumeActiveCount:rawAfterResume.correction_sessions.filter((x:any)=>x.status==='active').length,beforeCompleteStatus:beforeComplete.session.status,completedStatus:completed.status,completedAt:completed.completed_at,rereadId:reread.session?.id,rereadStatus:reread.session?.status,rereadCompletedAt:reread.session?.completed_at,finalSessionCount:rawFinal.correction_sessions.length,pending:pending.map((x:any)=>({state:x.payload.state,score:x.payload.score,status:x.status}))};
  },{qpath:queuePath,fpath:flowPath,startedId:beforeReload.startedId,order:beforeReload.order});

  expect(afterReload.recoveredBeforeResume.id).toBe(beforeReload.startedId);expect(afterReload.resumedId).toBe(beforeReload.startedId);expect(afterReload.recoveredBeforeResume.status).toBe('active');expect(afterReload.recoveredBeforeResume.position).toBe(beforeReload.position);expect(afterReload.beforeCompleteStatus).toBe('active');expect(afterReload.resumeSessionCount).toBe(1);expect(afterReload.resumeActiveCount).toBe(1);expect(afterReload.completedStatus).toBe('completed');expect(afterReload.completedAt).toBeTruthy();expect(afterReload.rereadId).toBe(beforeReload.startedId);expect(afterReload.rereadStatus).toBe('completed');expect(afterReload.rereadCompletedAt).toBe(afterReload.completedAt);expect(afterReload.finalSessionCount).toBe(1);
  expect(afterReload.pending).toHaveLength(39);expect(afterReload.pending.every((x:any)=>x.status==='PENDING_SAFE')).toBe(true);expect(afterReload.pending.some((x:any)=>x.state==='GRADED'&&x.score===0)).toBe(true);expect(afterReload.pending.some((x:any)=>x.state==='GRADED'&&x.score===-5)).toBe(true);expect(afterReload.pending.some((x:any)=>x.state==='MISSING'&&x.score===null)).toBe(true);expect(afterReload.pending.some((x:any)=>x.state==='EXCUSED'&&x.score===null)).toBe(true);expect(afterReload.pending.some((x:any)=>x.score===0&&x.state!=='GRADED')).toBe(false);expect(beforeReload.handled.some((x:any)=>x[1]==='SKIP'&&x[2]===null)).toBe(true);
});

test('conflict snapshot and both explicit resolutions remain causally coherent',async({page})=>{const result=await page.evaluate(async p=>{const m=await import(p),db=new m.SafeWorkDb('conflict-resolution');await db.operations.clear();const first=await m.enqueueAssessmentJudgement(db,{authUserId:'u',workspaceId:'w',assessmentId:'a',enrollmentId:'e',state:'GRADED',score:7,attemptKind:'CORRECTION',rawScore:7,expectedRevision:1,opId:'00000000-0000-0000-0000-000000000001'});await m.markOperation(db,first.op_id,{status:'CONFLICT',last_error_code:'REVISION_CONFLICT',conflict_snapshot:{canonical_state:'GRADED',canonical_score:8,canonical_revision:3}});await m.enqueueAssessmentJudgement(db,{authUserId:'u',workspaceId:'w',assessmentId:'a',enrollmentId:'e',state:'GRADED',score:9,attemptKind:'CORRECTION',rawScore:9,expectedRevision:2,opId:'00000000-0000-0000-0000-000000000002'});const snap=await db.operations.get(first.op_id),replacement=await m.applyLocalAsNewJudgement(db,first.op_id),afterLocal=await db.operations.where('[auth_user_id+workspace_id+causal_key]').equals(['u','w','assessment_result:a:e']).sortBy('created_at');await m.markOperation(db,replacement.op_id,{status:'CONFLICT',conflict_snapshot:{canonical_state:'MISSING',canonical_score:null,canonical_revision:5}});await m.useServerForConflict(db,replacement.op_id);const afterServer=await db.operations.where('[auth_user_id+workspace_id+causal_key]').equals(['u','w','assessment_result:a:e']).sortBy('created_at');db.close();return{snap,replacement,afterLocal,afterServer};},queuePath);expect(result.snap.conflict_snapshot).toEqual({canonical_state:'GRADED',canonical_score:8,canonical_revision:3});expect(result.replacement.op_id).not.toBe('00000000-0000-0000-0000-000000000001');expect(result.replacement.expected_revision).toBe(3);expect(result.afterLocal.map((x:any)=>x.expected_revision).sort()).toEqual([3,4]);expect(result.afterServer).toHaveLength(1);expect(result.afterServer[0].expected_revision).toBe(5);expect(result.afterServer[0].status).toBe('PENDING_SAFE');});
test('Dexie commit failure never returns Pending Safe',async({page})=>{const result=await page.evaluate(async p=>{const m=await import(p);const db=new m.SafeWorkDb('forced-failure');db.transaction=async()=>{throw new Error('forced dexie failure')};try{await m.enqueueAssessmentJudgement(db,{authUserId:'u',workspaceId:'w',assessmentId:'a',enrollmentId:'e',state:'GRADED',score:1,attemptKind:'CORRECTION',rawScore:1,expectedRevision:0});return'claimed';}catch{return'failed-before-pending-safe';}},queuePath);expect(result).toBe('failed-before-pending-safe');});
