import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import { StatusPanel } from '../components/StatusPanel';
import { readBrowserConfig } from '../config/env';
import { EXPECTED_SCHEMA_VERSION } from '../config/schema';
import { getSupabaseClient } from '../services/supabase/client';
import { initialAuthSnapshot, loadSession, signInWithPassword, signOut, subscribeToAuth, type AuthSnapshot } from '../services/auth/auth';
import { checkSchemaCompatibility, type SchemaCompatibility } from '../services/schema/schemaCompatibility';
import { hasUnsyncedForUser, safeWorkDb } from '../services/safeWork/localQueue';
function SignedOut({client,authError}:{client:SupabaseClient;authError:string|null}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState(authError);const[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(await signInWithPassword(client,email.trim(),password));setBusy(false);}return <main className="app-shell"><section className="auth-card"><p className="eyebrow">Nilai SMP · R3</p><h1>Masuk</h1><form onSubmit={submit} className="auth-form"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Kata sandi<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error?<p className="form-error" role="alert">Gagal masuk: {error}</p>:null}<button disabled={busy}>{busy?'Memeriksa…':'Masuk'}</button></form></section></main>}
function SignedIn({client,email,userId}:{client:SupabaseClient;email:string;userId:string}){const[schema,setSchema]=useState<SchemaCompatibility|null>(null);const[logoutError,setLogoutError]=useState<string|null>(null);useEffect(()=>{let active=true;void checkSchemaCompatibility(client,EXPECTED_SCHEMA_VERSION).then(r=>{if(active)setSchema(r)});return()=>{active=false}},[client]);async function logout(){if(await hasUnsyncedForUser(safeWorkDb,userId)){const ok=window.confirm('Ada pekerjaan yang sudah aman di perangkat tetapi belum tersimpan ke server. Pekerjaan itu akan tetap disimpan di browser ini dan tidak terlihat oleh akun lain. Tetap keluar?');if(!ok)return;}setLogoutError(await signOut(client));}if(!schema)return <main className="app-shell"><StatusPanel title="Memeriksa kompatibilitas data…"><p>Memverifikasi versi schema.</p></StatusPanel></main>;if(schema.status==='incompatible')return <main className="app-shell"><StatusPanel title="Database belum kompatibel" tone="error"><p>{schema.reason}</p><button onClick={logout}>Keluar</button></StatusPanel></main>;return <main className="app-shell"><section className="workspace-placeholder"><div><p className="eyebrow">Safe Work foundation ready</p><h1>Nilai SMP</h1><p className="muted">Masuk sebagai {email}. R3.2 menyediakan recovery queue; bukan full offline.</p></div><button type="button" className="secondary" onClick={logout}>Keluar</button>{logoutError?<p className="form-error" role="alert">Gagal keluar: {logoutError}</p>:null}</section></main>}
export function App(){const configResult=useMemo(()=>readBrowserConfig(),[]);const client=useMemo(()=>configResult.ok?getSupabaseClient(configResult.config):null,[configResult]);const[auth,setAuth]=useState<AuthSnapshot>(initialAuthSnapshot);useEffect(()=>{if(!client)return;let active=true;void loadSession(client).then(s=>{if(active)setAuth(s)});const sub=subscribeToAuth(client,s=>{if(active)setAuth(s)});return()=>{active=false;sub.unsubscribe()}},[client]);if(!configResult.ok)return <main className="app-shell"><StatusPanel title="Konfigurasi belum siap" tone="error"><p>Browser configuration tidak lengkap atau tidak aman.</p></StatusPanel></main>;if(!client||auth.status==='loading')return <main className="app-shell"><StatusPanel title="Memuat sesi…"><p>Memulihkan sesi Supabase Auth.</p></StatusPanel></main>;if(auth.status==='signed-out')return <SignedOut client={client} authError={auth.error}/>;return <SignedIn client={client} userId={auth.session.user.id} email={auth.session.user.email??auth.session.user.id}/>;}
