import{useEffect,useMemo,useState}from'react';
import type{SupabaseClient}from'@supabase/supabase-js';
import{appendArtifactVersion,archiveArtifact,createArtifact,isArtifactVersionStale,loadArtifactWorkspace,reserveArtifactObject,signedArtifactUrl,uploadArtifactObject,type ArtifactObjectKind,type ArtifactSourceKind,type ArtifactType,type ArtifactVersion,type ArtifactWorkspace}from'../services/artifacts/artifacts';

type Props={client:SupabaseClient;workspaceId:string};
type Draft={artifactId:string|null;artifactType:ArtifactType;title:string;source:string;canonicalText:string};
const blankDraft=():Draft=>({artifactId:null,artifactType:'RPP',title:'',source:'MANUAL',canonicalText:''});
function sourceInput(source:string):{sourceKind:ArtifactSourceKind;lessonId:null|string;lessonVersionId:null|string;reportSnapshotId:null|string}{
  if(source.startsWith('LESSON:')){const[,lessonId,lessonVersionId]=source.split(':');return{sourceKind:'LESSON_VERSION',lessonId,lessonVersionId,reportSnapshotId:null};}
  if(source.startsWith('REPORT:'))return{sourceKind:'REPORT_SNAPSHOT',lessonId:null,lessonVersionId:null,reportSnapshotId:source.slice(7)};
  return{sourceKind:'MANUAL',lessonId:null,lessonVersionId:null,reportSnapshotId:null};
}
function sourceLabel(version:ArtifactVersion,workspace:ArtifactWorkspace){
  if(version.source_kind==='MANUAL')return'Manual';
  if(version.source_kind==='REPORT_SNAPSHOT'){const source=workspace.reportSources.find(item=>item.id===version.report_snapshot_id);return source?`Report snapshot #${source.snapshot_no} · ${source.kind}`:'Report snapshot';}
  const source=workspace.lessonSources.find(item=>item.lesson_version_id===version.lesson_version_id);return source?`${source.lesson_title} · Lesson v${source.version_number}`:'Lesson version';
}
function mimeFor(kind:ArtifactObjectKind){if(kind==='PDF')return'application/pdf';if(kind==='DOCX')return'application/vnd.openxmlformats-officedocument.wordprocessingml.document';return'application/octet-stream';}

export function Artifacts({client,workspaceId}:Props){
  const[data,setData]=useState<ArtifactWorkspace|null>(null);const[draft,setDraft]=useState<Draft|null>(null);const[selectedId,setSelectedId]=useState('');const[notice,setNotice]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[showArchived,setShowArchived]=useState(false);const[file,setFile]=useState<File|null>(null);const[objectKind,setObjectKind]=useState<ArtifactObjectKind>('PDF');
  async function reload(){const next=await loadArtifactWorkspace(client,workspaceId);setData(next);setSelectedId(current=>next.artifacts.some(item=>item.id===current)?current:(next.artifacts.find(item=>item.status==='active')?.id??next.artifacts[0]?.id??''));}
  useEffect(()=>{void reload().catch(e=>setError(e instanceof Error?e.message:String(e)));},[client,workspaceId]);
  const selected=useMemo(()=>data?.artifacts.find(item=>item.id===selectedId)??null,[data,selectedId]);
  const versions=useMemo(()=>data&&selected?data.versions.filter(item=>item.artifact_id===selected.id).sort((a,b)=>b.version_no-a.version_no):[],[data,selected]);
  const current=useMemo(()=>selected?versions.find(item=>item.id===selected.current_version_id)??versions[0]??null:null,[selected,versions]);
  const objects=useMemo(()=>data&&current?data.objects.filter(item=>item.artifact_version_id===current.id):[],[data,current]);
  const visibleArtifacts=useMemo(()=>data?.artifacts.filter(item=>showArchived||item.status==='active')??[],[data,showArchived]);

  function selectSource(value:string,base:Draft){
    const next={...base,source:value};
    if(value.startsWith('LESSON:')){const versionId=value.split(':')[2];const source=data?.lessonSources.find(item=>item.lesson_version_id===versionId);if(source&&(!base.canonicalText.trim()||base.artifactId===null))next.canonicalText=source.content_text;}
    setDraft(next);
  }
  function startNew(){setDraft(blankDraft());setNotice(null);setError(null);}
  function startVersion(){if(!selected||!current)return;let source='MANUAL';if(current.source_kind==='LESSON_VERSION')source=`LESSON:${current.lesson_id}:${current.lesson_version_id}`;if(current.source_kind==='REPORT_SNAPSHOT')source=`REPORT:${current.report_snapshot_id}`;setDraft({artifactId:selected.id,artifactType:selected.artifact_type,title:selected.title,source,canonicalText:current.canonical_text});setNotice(null);setError(null);}
  async function save(){if(!draft||busy)return;if(!draft.title.trim()){setError('Judul artifact wajib.');return;}const src=sourceInput(draft.source);setBusy(true);setError(null);setNotice(null);try{if(draft.artifactId){const art=data?.artifacts.find(item=>item.id===draft.artifactId);if(!art)throw new Error('Artifact tidak ditemukan.');const result=await appendArtifactVersion(client,{opId:crypto.randomUUID(),artifactId:art.id,expectedRevision:art.revision,...src,canonicalText:draft.canonicalText,structuredContent:{}});if(result.outcome==='conflict'){await reload();throw new Error('Artifact berubah di tempat lain. Data terbaru dimuat; cek ulang sebelum membuat versi baru.');}setNotice(`Versi ${result.version_no} dibuat. Versi sebelumnya tetap utuh.`);}else{const result=await createArtifact(client,{opId:crypto.randomUUID(),artifactType:draft.artifactType,title:draft.title.trim(),...src,canonicalText:draft.canonicalText,structuredContent:{}});setSelectedId(result.artifact_id);setNotice('Artifact dibuat dengan version 1.');}setDraft(null);await reload();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function archive(){if(!selected||busy||!window.confirm(`Archive ${selected.title}? History tetap disimpan.`))return;setBusy(true);setError(null);try{const result=await archiveArtifact(client,{opId:crypto.randomUUID(),artifactId:selected.id,expectedRevision:selected.revision});if(result.outcome==='conflict'){await reload();throw new Error('Artifact berubah di tempat lain. Data terbaru dimuat.');}setNotice('Artifact di-archive. History dan object tetap utuh.');await reload();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function upload(){if(!selected||!current||!file||busy)return;setBusy(true);setError(null);setNotice(null);try{if(objectKind==='PDF'&&!file.name.toLowerCase().endsWith('.pdf'))throw new Error('Pilih file .pdf untuk object PDF.');if(objectKind==='DOCX'&&!file.name.toLowerCase().endsWith('.docx'))throw new Error('Pilih file .docx untuk object DOCX.');const expectedMime=mimeFor(objectKind);let object=objects.find(item=>item.object_kind===objectKind);let reservation:{objectId:string;storagePath:string};if(object?.state==='READY')throw new Error(`${objectKind} version ini sudah READY. Buat artifact version baru untuk regenerasi, jangan overwrite.`);if(object){if(object.byte_size!==file.size||object.mime_type!==expectedMime)throw new Error('Pending upload ini terikat ke ukuran/jenis file sebelumnya. Gunakan file yang sama atau buat artifact version baru; metadata lama tidak akan ditimpa.');reservation={objectId:object.id,storagePath:object.storage_path};}else{const reserved=await reserveArtifactObject(client,{opId:crypto.randomUUID(),artifactId:selected.id,artifactVersionId:current.id,objectKind,mimeType:expectedMime,byteSize:file.size});reservation={objectId:reserved.object_id,storagePath:reserved.storage_path};}const hash=await uploadArtifactObject(client,reservation,file);setNotice(`${objectKind} READY · SHA-256 ${hash.slice(0,12)}…`);setFile(null);await reload();}catch(e){setError(e instanceof Error?e.message:String(e));await reload().catch(()=>{});}finally{setBusy(false);}}
  async function download(path:string){setBusy(true);setError(null);try{const url=await signedArtifactUrl(client,path);window.open(url,'_blank','noopener,noreferrer');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}

  if(!data)return<section className="continuity-shell"><p>Memuat artifacts…</p>{error?<p role="alert" className="form-error">{error}</p>:null}</section>;
  return<section className="continuity-shell artifact-shell"><header><p className="eyebrow">Artifacts · persistent teacher documents</p><h1>Artifact history, bukan file sekali pakai</h1><p className="muted">RPP, Modul Ajar, LKPD, Silabus, ATP. Manual tetap first-class; AI tidak diperlukan.</p></header>
    <div className="artifact-toolbar"><button type="button" onClick={startNew}>Artifact baru</button><label><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/> Tampilkan archived</label></div>
    {visibleArtifacts.length?<label className="field-label">Artifact<select value={selectedId} onChange={e=>{setSelectedId(e.target.value);setDraft(null);setFile(null);}}>{visibleArtifacts.map(item=><option value={item.id} key={item.id}>{item.artifact_type} · {item.title}{item.status==='archived'?' · ARCHIVED':''}</option>)}</select></label>:<div className="continuity-empty"><strong>Belum ada artifact.</strong><p>Buat satu dari teks manual atau exact LessonVersion.</p></div>}
    {selected&&current?<div className="artifact-current checkpoint-card"><div className="continuity-status"><strong>{selected.artifact_type} · {selected.title}</strong><span>v{current.version_no}{isArtifactVersionStale(current,data)?' · STALE SOURCE':''}</span></div><p className="muted">Source: {sourceLabel(current,data)} · stable artifact {selected.id.slice(0,8)}…</p><div className="artifact-text">{current.canonical_text||'— teks kosong —'}</div><p className="muted">History: {versions.length} version. Regeneration selalu membuat version baru.</p>{selected.status==='active'?<div className="today-actions"><button className="secondary" type="button" onClick={startVersion}>Buat versi baru</button><button className="secondary" type="button" onClick={()=>void archive()}>Archive</button></div>:null}</div>:null}
    {draft?<div className="checkpoint-card"><h2>{draft.artifactId?'Artifact version baru':'Artifact baru'}</h2>{!draft.artifactId?<label className="field-label">Jenis<select value={draft.artifactType} onChange={e=>setDraft({...draft,artifactType:e.target.value as ArtifactType})}>{['RPP','MODUL_AJAR','LKPD','SILABUS','ATP','OTHER'].map(type=><option key={type}>{type}</option>)}</select></label>:null}<label className="field-label">Judul<input value={draft.title} disabled={Boolean(draft.artifactId)} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field-label">Exact source<select value={draft.source} onChange={e=>selectSource(e.target.value,draft)}><option value="MANUAL">Manual / tidak bergantung AI</option>{data.lessonSources.map(item=><option key={item.lesson_version_id} value={`LESSON:${item.lesson_id}:${item.lesson_version_id}`}>{item.lesson_title} · Lesson v{item.version_number}</option>)}{data.reportSources.map(item=><option key={item.id} value={`REPORT:${item.id}`}>Report snapshot #{item.snapshot_no} · {item.kind}</option>)}</select></label><label className="field-label">Canonical text<textarea rows={12} value={draft.canonicalText} onChange={e=>setDraft({...draft,canonicalText:e.target.value})}/></label><div className="today-actions"><button disabled={busy} type="button" onClick={()=>void save()}>Simpan {draft.artifactId?'version baru':'artifact'}</button><button disabled={busy} className="secondary" type="button" onClick={()=>setDraft(null)}>Batal</button></div></div>:null}
    {selected&&current?<div className="checkpoint-card"><h2>DOCX / PDF objects · current version</h2><p className="muted">Object private. READY memakai checksum; overwrite dilarang. Regenerasi = artifact version baru.</p>{objects.map(object=><div className="artifact-object" key={object.id}><strong>{object.object_kind}</strong><span>{object.state}</span><span>{object.state==='READY'?`${object.byte_size} B · ${object.sha256?.slice(0,12)}…`:'Upload belum dikonfirmasi'}</span>{object.state==='READY'?<button type="button" className="secondary" disabled={busy} onClick={()=>void download(object.storage_path)}>Buka signed link</button>:null}</div>)}<label className="field-label">Object kind<select value={objectKind} onChange={e=>setObjectKind(e.target.value as ArtifactObjectKind)}><option>PDF</option><option>DOCX</option><option>OTHER</option></select></label><label className="field-label">File<input type="file" onChange={e=>setFile(e.target.files?.[0]??null)} /></label><button type="button" disabled={busy||!file} onClick={()=>void upload()}>{objects.find(item=>item.object_kind===objectKind)?.state==='PENDING_UPLOAD'?'Retry upload':'Upload private object'}</button></div>:null}
    {notice?<p role="status" className="work-message">{notice}</p>:null}{error?<p role="alert" className="form-error">{error}</p>:null}
  </section>;
}
