import{useState}from'react';
import type{SupabaseClient}from'@supabase/supabase-js';
import{backupBlob,generatePortableBackup,makeHumanEscapeXlsx,restorePortableBackup,verifyPortableBackup,type PortableBackup}from'../services/recovery/portableBackup';

type Props={client:SupabaseClient};
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function stamp(){return new Date().toISOString().replace(/[:.]/g,'-');}

export function BackupRestore({client}:Props){
  const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);const[lastBackup,setLastBackup]=useState<PortableBackup|null>(null);const[file,setFile]=useState<File|null>(null);const[verified,setVerified]=useState<PortableBackup|null>(null);const[confirmRestore,setConfirmRestore]=useState(false);
  async function createBackup(){setBusy(true);setError(null);setNotice(null);try{const backup=await generatePortableBackup(client);setLastBackup(backup);download(backupBlob(backup),`nilai-smp-backup-${stamp()}.json`);setNotice(`Backup portable terverifikasi dibuat. Artifact payload: ${backup.artifact_payloads.length}. Simpan file ini di luar provider.`);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function verifyFile(next:File|null){setFile(next);setVerified(null);setConfirmRestore(false);setError(null);setNotice(null);if(!next)return;if(next.size>80_000_000){setError('File backup melebihi batas 80 MB.');return;}setBusy(true);try{const parsed=JSON.parse(await next.text());const backup=await verifyPortableBackup(parsed);setVerified(backup);setNotice(`Checksum valid · schema sumber ${backup.source_schema_version} · ${Object.values(backup.tables).reduce((n,rows)=>n+rows.length,0)} row canonical · ${backup.artifact_payloads.length} artifact payload.`);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function restore(){if(!verified||!confirmRestore||busy)return;setBusy(true);setError(null);setNotice(null);try{const result=await restorePortableBackup(client,verified);setNotice(`Restore selesai${result.replayed?' (replay aman)':''}: ${result.restoredRows} row canonical, ${result.artifactPayloads} artifact payload. Reload aplikasi untuk membaca canonical truth.`);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  return <section className="continuity-shell"><header><p className="eyebrow">Recovery · portable truth</p><h1>Backup / Restore</h1><p className="muted">Archive bukan backup. File ini membawa canonical rows + byte ArtifactObject READY dengan SHA-256, sehingga keluar dari provider tetap mungkin.</p></header>
    <div className="checkpoint-card"><h2>1. Buat portable backup</h2><p>Export berhenti bila checksum artifact tidak cocok. Tidak ada klaim “backup sukses” bila byte READY tidak bisa dibaca.</p><button type="button" disabled={busy} onClick={()=>void createBackup()}>{busy?'Memproses…':'Buat & download backup JSON'}</button>{lastBackup?<button type="button" className="secondary" onClick={()=>download(makeHumanEscapeXlsx(lastBackup),`nilai-smp-human-escape-${stamp()}.xlsx`)}>Download Excel human escape</button>:null}</div>
    <div className="checkpoint-card"><h2>2. Verifikasi / restore</h2><p className="muted">Restore hanya diterima ke workspace canonical yang kosong. Stable domain IDs dipertahankan; workspace ownership dipetakan ke akun yang sedang login. Artifact binary dikembalikan sebagai PENDING dulu dan baru READY setelah byte + SHA-256 terkonfirmasi.</p><label className="field-label">Portable backup JSON<input type="file" accept="application/json,.json" onChange={e=>void verifyFile(e.target.files?.[0]??null)}/></label>{verified?<><p><strong>VALID</strong> · format v{verified.format_version} · {verified.source_schema_version}</p><label><input type="checkbox" checked={confirmRestore} onChange={e=>setConfirmRestore(e.target.checked)}/> Saya paham restore hanya untuk workspace kosong dan tidak menimpa data existing.</label><div><button type="button" disabled={busy||!confirmRestore} onClick={()=>void restore()}>Restore verified backup</button></div></>:file&&!busy?<p>File belum lolos verifikasi.</p>:null}</div>
    {notice?<p role="status" className="work-message">{notice}</p>:null}{error?<p role="alert" className="form-error">{error}</p>:null}
  </section>;
}
