import{useState}from'react';
import type{SupabaseClient}from'@supabase/supabase-js';
import{backupBlob,generatePortableBackup,makeHumanEscapeXlsx,restorePortableBackup,verifyPortableBackup,type PortableBackup}from'../services/recovery/portableBackup';

type Props={client:SupabaseClient};
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function stamp(){return new Date().toISOString().replace(/[:.]/g,'-');}

export function BackupRestore({client}:Props){
  const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);const[lastBackup,setLastBackup]=useState<PortableBackup|null>(null);const[file,setFile]=useState<File|null>(null);const[verified,setVerified]=useState<PortableBackup|null>(null);const[confirmRestore,setConfirmRestore]=useState(false);
  async function createBackup(){setBusy(true);setError(null);setNotice(null);try{const backup=await generatePortableBackup(client);setLastBackup(backup);download(backupBlob(backup),`nilai-smp-backup-${stamp()}.json`);setNotice(`Cadangan portabel terverifikasi dibuat. Muatan dokumen: ${backup.artifact_payloads.length}. Simpan file ini di luar penyedia layanan.`);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function verifyFile(next:File|null){setFile(next);setVerified(null);setConfirmRestore(false);setError(null);setNotice(null);if(!next)return;if(next.size>80_000_000){setError('File cadangan melebihi batas 80 MB.');return;}setBusy(true);try{const parsed=JSON.parse(await next.text());const backup=await verifyPortableBackup(parsed);setVerified(backup);setNotice(`Checksum valid · skema sumber ${backup.source_schema_version} · ${Object.values(backup.tables).reduce((n,rows)=>n+rows.length,0)} baris kanonik · ${backup.artifact_payloads.length} muatan dokumen.`);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function restore(){if(!verified||!confirmRestore||busy)return;setBusy(true);setError(null);setNotice(null);try{const result=await restorePortableBackup(client,verified);setNotice(`Pemulihan selesai${result.replayed?' (pengulangan aman)':''}: ${result.restoredRows} baris kanonik, ${result.artifactPayloads} muatan dokumen. Muat ulang aplikasi untuk membaca data kanonik terbaru.`);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  return <section className="continuity-shell"><header><p className="eyebrow">Pemulihan · cadangan portabel</p><h1>Cadangan / Pemulihan</h1><p className="muted">Arsip bukan cadangan. File ini membawa baris kanonik dan byte dokumen berstatus READY dengan SHA-256, sehingga data tetap dapat dibawa keluar dari penyedia layanan.</p></header>
    <div className="checkpoint-card"><h2>1. Buat cadangan portabel</h2><p>Ekspor dihentikan bila checksum dokumen tidak cocok. Tidak ada klaim “cadangan berhasil” bila byte berstatus READY tidak dapat dibaca.</p><button type="button" disabled={busy} onClick={()=>void createBackup()}>{busy?'Memproses…':'Buat & unduh cadangan JSON'}</button>{lastBackup?<button type="button" className="secondary" onClick={()=>download(makeHumanEscapeXlsx(lastBackup),`nilai-smp-human-escape-${stamp()}.xlsx`)}>Unduh Excel darurat</button>:null}</div>
    <div className="checkpoint-card"><h2>2. Verifikasi / pulihkan</h2><p className="muted">Pemulihan hanya diterima ke ruang kerja kanonik yang kosong. ID domain stabil dipertahankan; kepemilikan ruang kerja dipetakan ke akun yang sedang masuk. Byte dokumen dikembalikan sebagai PENDING terlebih dahulu dan baru menjadi READY setelah byte + SHA-256 terkonfirmasi.</p><label className="field-label">Cadangan portabel JSON<input type="file" accept="application/json,.json" onChange={e=>void verifyFile(e.target.files?.[0]??null)}/></label>{verified?<><p><strong>VALID</strong> · format v{verified.format_version} · {verified.source_schema_version}</p><label><input type="checkbox" checked={confirmRestore} onChange={e=>setConfirmRestore(e.target.checked)}/> Saya paham pemulihan hanya untuk ruang kerja kosong dan tidak menimpa data yang sudah ada.</label><div><button type="button" disabled={busy||!confirmRestore} onClick={()=>void restore()}>Pulihkan cadangan terverifikasi</button></div></>:file&&!busy?<p>File belum lolos verifikasi.</p>:null}</div>
    {notice?<p role="status" className="work-message">{notice}</p>:null}{error?<p role="alert" className="form-error">{error}</p>:null}
  </section>;
}
