import {useEffect,useMemo,useState} from 'react';
import type{SupabaseClient}from'@supabase/supabase-js';
import type{Assessment,Result}from'../domain/academic';
import type{PendingOperation}from'../domain/safeWork';
import{loadCorrectionContext,startOrResumeCorrection,setCorrectionPosition,completeCorrection,searchCorrectionStudents,queueCorrectionJudgement,type CorrectionContext}from'../services/academic/rapidCorrection';
import{discardOperation,pendingForNamespace,retryOperation,safeWorkDb}from'../services/safeWork/localQueue';
import{SafeWorkSyncWorker}from'../services/safeWork/syncWorker';
export function RapidCorrection({client,userId,workspaceId}:{client:SupabaseClient;userId:string;workspaceId:string}){
 const[assessments,setAssessments]=useState<Assessment[]>([]),[assessmentId,setAssessmentId]=useState(''),[ctx,setCtx]=useState<CorrectionContext|null>(null),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[score,setScore]=useState(''),[ops,setOps]=useState<PendingOperation[]>([]),[message,setMessage]=useState(''),[lastOp,setLastOp]=useState<string|null>(null);
 const worker=useMemo(()=>new SafeWorkSyncWorker(safeWorkDb,client),[client]);
 async function refreshOps(){setOps(await pendingForNamespace(safeWorkDb,userId,workspaceId));}
 useEffect(()=>{void client.from('assessments').select('*').eq('workspace_id',workspaceId).eq('status','active').then(({data})=>{const rows=(data??[])as Assessment[];setAssessments(rows);if(rows[0])setAssessmentId(x=>x||rows[0].id);});},[client,workspaceId]);
 useEffect(()=>{if(!assessmentId)return;void loadCorrectionContext(client,workspaceId,assessmentId).then(setCtx);void refreshOps();},[assessmentId,client,workspaceId]);
 const choices=ctx?searchCorrectionStudents(ctx,query):[];const currentResult=ctx?.results.find(r=>r.enrollment_id===selected)??null;
 const handled=ctx?.results.filter(r=>r.state!=='UNCHECKED').length??0,unchecked=(ctx?.enrollments.length??0)-handled;
 async function begin(){if(!ctx)return;const session=await startOrResumeCorrection(client,workspaceId,ctx.assessment,ctx.session);setCtx({...ctx,session});setMessage('Sesi koreksi aktif.');}
 async function selectEnrollment(id:string){if(!ctx?.session)return;setSelected(id);setQuery('');setScore('');const session=await setCorrectionPosition(client,ctx.session,id);setCtx({...ctx,session});}
 async function judge(state:Result['state']){if(!ctx||!selected)return;let numeric:number|null=null;if(state==='GRADED'){if(score.trim()===''){setMessage('Nilai wajib diisi untuk GRADED.');return;}numeric=Number(score);if(!Number.isFinite(numeric)){setMessage('Nilai harus berupa angka.');return;}}
   try{const op=await queueCorrectionJudgement(safeWorkDb,{authUserId:userId,workspaceId,assessmentId:ctx.assessment.id,enrollmentId:selected,state,score:numeric,result:currentResult});setLastOp(op.op_id);setMessage('Pending Safe — sudah durabel di perangkat. Lanjut ke kertas berikutnya.');setSelected('');setScore('');await refreshOps();void worker.syncNamespace(userId,workspaceId).then(async()=>{await refreshOps();setCtx(await loadCorrectionContext(client,workspaceId,assessmentId));});}catch(e){setMessage(`Belum Pending Safe: ${e instanceof Error?e.message:'IndexedDB gagal'}`);}}
 async function skip(){setMessage('Dilewati: tetap UNCHECKED.');setSelected('');setScore('');}
 async function undo(){if(!lastOp)return;const found=await safeWorkDb.operations.get(lastOp);if(found){await discardOperation(safeWorkDb,lastOp);setMessage('Judgement lokal terakhir dibatalkan sebelum Saved.');setLastOp(null);await refreshOps();}else setMessage('Judgement terakhir sudah Saved; pilih siswa dan rekam koreksi eksplisit.');}
 async function retry(opId:string){await retryOperation(safeWorkDb,opId);await worker.syncNamespace(userId,workspaceId);await refreshOps();}
 async function discard(opId:string){await discardOperation(safeWorkDb,opId);await refreshOps();setMessage('Perubahan lokal dibuang; server tetap canonical.');}
 async function finish(){if(!ctx?.session)return;const session=await completeCorrection(client,ctx.session);setCtx({...ctx,session});setMessage('Sesi koreksi selesai secara eksplisit.');}
 return <section className="correction-shell"><header><p className="eyebrow">Rapid Correction · Pending Safe</p><h1>Koreksi</h1><select aria-label="Assessment" value={assessmentId} onChange={e=>setAssessmentId(e.target.value)}>{assessments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></header>{ctx?<><div className="context-strip"><strong>{ctx.academicClass.display_name}</strong><span>{ctx.assessment.title}</span><span>{ctx.scoringProfile?.name??'Tanpa scoring profile'}</span><span>Handled {handled} · Unchecked {unchecked}</span></div>{!ctx.session||ctx.session.status==='completed'?<button onClick={begin}>Start correction</button>:<><label>Cari pemilik kertas<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nama / NIS / NISN"/></label>{query||!selected?<div className="student-results">{choices.slice(0,12).map(({student,enrollment})=><button className="student-choice" key={enrollment.id} onClick={()=>selectEnrollment(enrollment.id)}><strong>{student.display_name}</strong><small>{student.nis||student.nisn||enrollment.id.slice(0,8)} · {enrollment.id.slice(0,8)}</small></button>)}</div>:null}{selected?<div className="judge-card"><strong>{choices.find(x=>x.enrollment.id===selected)?.student.display_name??ctx.students.find(s=>s.id===ctx.enrollments.find(e=>e.id===selected)?.student_id)?.display_name}</strong><input inputMode="decimal" value={score} onChange={e=>setScore(e.target.value)} placeholder="Nilai (0 dan negatif valid)"/><div className="judge-actions"><button onClick={()=>judge('GRADED')}>Simpan nilai</button><button onClick={()=>judge('MISSING')}>Missing</button><button onClick={()=>judge('EXCUSED')}>Excused</button><button className="secondary" onClick={skip}>Skip</button></div></div>:null}<div className="session-actions"><button className="secondary" disabled={!lastOp} onClick={undo}>Undo lokal terakhir</button><button className="secondary" onClick={finish}>Selesaikan sesi</button></div></>}</>:<p>Memuat assessment…</p>}{message?<p role="status" className="work-message">{message}</p>:null}{ops.length?<aside className="recovery-panel"><h2>Perlu sinkronisasi / pemulihan</h2>{ops.filter(o=>o.operation_kind==='assessment.judgement').map(op=><div key={op.op_id} className="recovery-item"><strong>{op.status}</strong><span>Siswa/enrollment {op.entity_id.slice(0,8)} · {(op.payload as any).state} {(op.payload as any).score??''}</span>{op.last_error_code?<small>{op.last_error_code}</small>:null}{op.status!=='PENDING_SAFE'?<div><button onClick={()=>retry(op.op_id)}>Retry</button><button className="secondary" onClick={()=>discard(op.op_id)}>Discard local</button></div>:null}</div>)}</aside>:null}</section>;
}
