import type{SupabaseClient}from'@supabase/supabase-js';
import type{Assessment,Enrollment,Result,ResultState,Student}from'../../domain/academic';
export const BULK_MAX_ROWS=500,BULK_MAX_FILE_BYTES=2_000_000;
export type BulkContext={assessment:Assessment;enrollments:Enrollment[];students:Student[];results:Result[]};
export type RawBulkRow={row:number;enrollmentId?:string;nis?:string;nisn?:string;name?:string;value:unknown};
export type BulkPreviewRow={row:number;enrollment:Enrollment|null;student:Student|null;raw:string;state:ResultState;score:number|null;expectedRevision:number;status:'VALID'|'AMBIGUOUS'|'UNMATCHED'|'ERROR';errors:string[];action:'create'|'change'|'no-op'};
export async function loadBulkContext(client:SupabaseClient,workspaceId:string,assessmentId:string):Promise<BulkContext>{const{data:a,error:ae}=await client.from('assessments').select('*').eq('workspace_id',workspaceId).eq('id',assessmentId).single();if(ae)throw ae;const assessment=a as Assessment;const[e,s,r]=await Promise.all([client.from('enrollments').select('*').eq('workspace_id',workspaceId).eq('class_id',assessment.class_id),client.from('students').select('*').eq('workspace_id',workspaceId),client.from('assessment_results').select('*').eq('workspace_id',workspaceId).eq('assessment_id',assessmentId)]);for(const q of[e,s,r])if(q.error)throw q.error;const enrollments=(e.data??[])as Enrollment[],ids=new Set(enrollments.map(x=>x.student_id));return{assessment,enrollments,students:((s.data??[])as Student[]).filter(x=>ids.has(x.id)),results:(r.data??[])as Result[]}}
export function interpretBulkValue(value:unknown):{state:ResultState;score:number|null;error?:string}{if(value===null||value===undefined||value==='')return{state:'UNCHECKED',score:null};if(typeof value==='number'&&Number.isFinite(value))return{state:'GRADED',score:value};if(typeof value!=='string')return{state:'UNCHECKED',score:null,error:'Nilai tidak didukung.'};const v=value.trim();if(!v)return{state:'UNCHECKED',score:null};if(/^MISSING$/i.test(v)||/^TIDAK ADA$/i.test(v))return{state:'MISSING',score:null};if(/^EXCUSED$/i.test(v)||/^IZIN$/i.test(v))return{state:'EXCUSED',score:null};if(/^-?(?:\d+\.?\d*|\.\d+)$/.test(v)){const n=Number(v);if(Number.isFinite(n))return{state:'GRADED',score:n}}return{state:'UNCHECKED',score:null,error:`Nilai "${v.slice(0,80)}" tidak valid.`}}
function candidates(ctx:BulkContext,row:RawBulkRow){if(row.enrollmentId)return ctx.enrollments.filter(e=>e.id===row.enrollmentId);const students=row.nisn?ctx.students.filter(s=>s.nisn===row.nisn):row.nis?ctx.students.filter(s=>s.nis===row.nis):[];const ids=new Set(students.map(s=>s.id));return ctx.enrollments.filter(e=>ids.has(e.student_id))}
export function previewBulkRows(ctx:BulkContext,rows:RawBulkRow[]):BulkPreviewRow[]{if(rows.length>BULK_MAX_ROWS)throw new Error(`Maksimal ${BULK_MAX_ROWS} baris.`);const seen=new Set<string>();return rows.map(row=>{const match=candidates(ctx,row),parsed=interpretBulkValue(row.value),errors:string[]=[];let status:BulkPreviewRow['status']='VALID',enrollment:Enrollment|null=null;if(match.length===0){status='UNMATCHED';errors.push('Identitas siswa tidak ditemukan di kelas Assessment ini.')}else if(match.length>1){status='AMBIGUOUS';errors.push('Identitas cocok ke lebih dari satu Enrollment.')}else{enrollment=match[0];if(seen.has(enrollment.id)){status='ERROR';errors.push('Enrollment muncul lebih dari sekali dalam file.')}seen.add(enrollment.id)}if(parsed.error){status='ERROR';errors.push(parsed.error)}const student=enrollment?ctx.students.find(s=>s.id===enrollment!.student_id)??null:null,current=enrollment?ctx.results.find(r=>r.enrollment_id===enrollment!.id)??null:null;let action:BulkPreviewRow['action']='create';if(parsed.state==='UNCHECKED')action='no-op';else if(current)action=current.state===parsed.state&&current.score===parsed.score?'no-op':'change';return{row:row.row,enrollment,student,raw:String(row.value??''),state:parsed.state,score:parsed.score,expectedRevision:current?.revision??0,status,errors,action}})}
export function rowsForCommit(preview:BulkPreviewRow[]){if(preview.some(r=>r.status!=='VALID'))throw new Error('Perbaiki semua error sebelum Commit.');return preview.filter(r=>r.action!=='no-op').map(r=>({enrollment_id:r.enrollment!.id,state:r.state,score:r.score,expected_revision:r.expectedRevision,attempt_kind:null,raw_score:null}))}
export async function commitBulkAssessment(client:SupabaseClient,assessmentId:string,opId:string,preview:BulkPreviewRow[]){const{data,error}=await client.rpc('apply_assessment_bulk_operation',{p_op_id:opId,p_assessment_id:assessmentId,p_rows:rowsForCommit(preview)});if(error)throw new Error(`Bulk commit gagal: ${error.message}`);const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error('Bulk commit tidak mengembalikan hasil.');return row as{outcome:'saved'|'conflict';replayed:boolean;summary:Record<string,number>|null;conflicts:unknown[]}}
export function templateRows(ctx:BulkContext){return ctx.enrollments.map(e=>{const s=ctx.students.find(x=>x.id===e.student_id)!;return{Assessment_ID:ctx.assessment.id,Enrollment_ID:e.id,NIS:s?.nis??'',NISN:s?.nisn??'',Nama:s?.display_name??'',Nilai:''}})}
export function parseCsv(text:string):RawBulkRow[]{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)throw new Error('File kosong.');const headers=lines[0].split(',').map(x=>x.trim());for(const h of['Assessment_ID','Enrollment_ID','Nilai'])if(!headers.includes(h))throw new Error(`Kolom wajib ${h} tidak ada.`);return lines.slice(1).map((line,i)=>{const cells=line.split(',');const get=(h:string)=>cells[headers.indexOf(h)]?.trim()??'';return{row:i+2,enrollmentId:get('Enrollment_ID'),nis:get('NIS'),nisn:get('NISN'),name:get('Nama'),value:get('Nilai')}})}
export function safeCsvCell(v:unknown){let s=String(v??'').replace(/"/g,'""');if(/^[=+\-@]/.test(s))s=`'${s}`;return`"${s}"`}
export function makeCsvTemplate(ctx:BulkContext){const rows=templateRows(ctx),headers=['Assessment_ID','Enrollment_ID','NIS','NISN','Nama','Nilai'];return[headers.join(','),...rows.map(r=>headers.map(h=>safeCsvCell((r as any)[h])).join(','))].join('\r\n')}
