import {readFileSync} from'node:fs';
import {describe,expect,it} from'vitest';
import{deriveTodayModel,type TodayClassContext,type TodayServerSnapshot}from'../../src/services/academic/today';
import type{PlannedSuggestion}from'../../src/services/academic/plannedTimetable';

const base=(patch:Partial<TodayClassContext>={}):TodayClassContext=>({class_id:'C1',class_name:'VIII A',active_meeting_id:null,active_meeting_occurred_at:null,active_lesson_title:null,latest_actual_meeting_id:null,latest_actual_meeting_occurred_at:null,latest_actual_meeting_status:null,active_checkpoint_id:null,active_checkpoint_stopped_at:null,active_checkpoint_next_step:null,active_checkpoint_recorded_at:null,latest_checkpoint_id:null,latest_checkpoint_meeting_id:null,latest_checkpoint_stopped_at:null,latest_checkpoint_next_step:null,latest_checkpoint_recorded_at:null,latest_baseline_id:null,latest_baseline_kind:null,latest_baseline_stopped_at:null,latest_baseline_next_step:null,latest_baseline_recorded_at:null,effective_source:null,effective_stopped_at:null,effective_next_step:null,effective_recorded_at:null,...patch});
const snap=(classes:TodayClassContext[],correction:TodayServerSnapshot['correction']=null):TodayServerSnapshot=>({classes,correction});
const planned=(classId='C2'):PlannedSuggestion=>({kind:'likely-now',slot:{schedule_id:'S1',class_id:classId,class_name:'VIII B',weekday:4,local_start_time:'09:00',local_end_time:'09:40',effective_from:'2026-07-01',status:'active'},ambiguous:[]});

describe('F1 Today integration',()=>{
 it('active Meeting remains stronger than planned schedule',()=>{const model=deriveTodayModel(snap([base({active_meeting_id:'M1'})]),[],new Date('2026-09-10T09:10:00'),planned());expect(model.primary).toEqual({kind:'continue-class',classId:'C1',label:'CONTINUE CLASS'});});
 it('active correction remains stronger than planned schedule',()=>{const correction={session_id:'CS',assessment_id:'A',assessment_title:'Kuis',class_id:'C1',class_name:'VIII A',current_enrollment_id:null,started_at:'2026-09-10',updated_at:'2026-09-10',active_count:1};const model=deriveTodayModel(snap([base()],correction),[],new Date('2026-09-10T09:10:00'),planned());expect(model.primary?.kind).toBe('resume-correction');});
 it('stale continuity requiring explicit repair remains stronger than planned schedule',()=>{const model=deriveTodayModel(snap([base({effective_stopped_at:'Bab 1',effective_recorded_at:'2026-01-01T00:00:00Z'})]),[],new Date('2026-09-10T09:10:00'),planned());expect(model.primary).toEqual({kind:'quick-update',classId:'C1',label:'QUICK UPDATE'});});
 it('planned class outranks ordinary manual/default start flow',()=>{const model=deriveTodayModel(snap([base()]),[],new Date('2026-09-10T09:10:00'),planned());expect(model.primary).toEqual({kind:'start-class',classId:'C2',label:'START CLASS'});});
 it('UI exposes timetable editor and never directly creates Meetings',()=>{const app=readFileSync('src/app/App.tsx','utf8');const editor=readFileSync('src/components/PlannedTimetable.tsx','utf8');const today=readFileSync('src/components/Today.tsx','utf8');expect(app).toContain('Jadwal Mengajar');expect(editor).toContain("from('planned_schedules')");expect(editor).not.toContain("from('meetings')");expect(today).toContain('loadPlannedScheduleContexts');expect(today).not.toContain("insert into public.meetings");});
});
