import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest';import{EXPECTED_SCHEMA_VERSION}from'../../src/config/schema';
const foundation=readFileSync('supabase/migrations/202609030001_foundation_schema_version.sql','utf8');const spine=readFileSync('supabase/migrations/202609040001_academic_spine.sql','utf8');const safe=readFileSync('supabase/migrations/202609040002_safe_work_engine.sql','utf8');const teaching=readFileSync('supabase/migrations/202609040003_teaching_core.sql','utf8');const assessment=readFileSync('supabase/migrations/202609040004_assessment_core.sql','utf8');const rapid=readFileSync('supabase/migrations/202609040005_rapid_correction_safe_writes.sql','utf8');const bulk=readFileSync('supabase/migrations/202609040006_bulk_assessment.sql','utf8');const continuity=readFileSync('supabase/migrations/202609050001_continuity_core.sql','utf8');const lifecycleGuard=readFileSync('supabase/migrations/202609050002_continuity_lifecycle_guard.sql','utf8');const writeBoundary=readFileSync('supabase/migrations/202609050003_continuity_write_boundary.sql','utf8');const today=readFileSync('supabase/migrations/202609060001_today_reentry.sql','utf8');const pacing=readFileSync('supabase/migrations/202609060002_pacing_final_torture.sql','utf8');const reporting=readFileSync('supabase/migrations/202609060003_reporting_core.sql','utf8');const artifacts=readFileSync('supabase/migrations/202609060004_artifact_core.sql','utf8');const artifactHardening=readFileSync('supabase/migrations/202609060005_artifact_integrity_hardening.sql','utf8');const artifactGovernor=readFileSync('supabase/migrations/202609060006_artifact_governor_repairs.sql','utf8');const recovery=readFileSync('supabase/migrations/202609070001_recovery_portable_backup.sql','utf8');
describe('migration contract',()=>{
  it('advances frontend schema identity append-only through Today, pacing, reporting, artifacts and recovery',()=>{expect(continuity).toContain("'r3.4-continuity-core.1'");expect(lifecycleGuard).toContain('r3.4-continuity-core.1');expect(writeBoundary).toContain("version='r3.4-continuity-core.1'");expect(today).toContain("'r3.4-today-reentry.1'");expect(pacing).toContain("'r3.4-pacing-final.1'");expect(reporting).toContain("'r3.5-reporting-core.1'");expect(artifacts).toContain("'r3.5-artifact-core.1'");expect(artifactHardening).toContain("'r3.5-artifact-core.2'");expect(artifactGovernor).toContain("'r3.5-artifact-core.3'");const finalSchemaWrite=recovery.lastIndexOf(`'${EXPECTED_SCHEMA_VERSION}'`);expect(finalSchemaWrite).toBeGreaterThan(-1);expect(recovery.indexOf('create or replace function public.restore_portable_backup_operation')).toBeLessThan(finalSchemaWrite)});
  it('keeps schema version read-only',()=>{expect(foundation).toContain('grant select on table public.app_schema_version to authenticated');expect(foundation).toContain('revoke insert, update, delete on table public.app_schema_version from authenticated')});
  it('preserves R3.1 spine RLS',()=>{for(const t of['workspaces','academic_years','academic_periods','classes','students','enrollments'])expect(spine).toContain(`alter table public.${t} enable row level security`)});
  it('preserves R3.2 applied-operation protection',()=>expect(safe).toContain('alter table public.applied_operations enable row level security'));
  it('protects every Teaching Core table with RLS',()=>{for(const t of['materials','lessons','lesson_versions','meetings','checkpoints','activities','activity_meetings'])expect(teaching).toContain(`alter table public.${t} enable row level security`)});
  it('protects every Assessment Core table with RLS',()=>{for(const t of['scoring_profiles','assessments','assessment_results','assessment_attempts'])expect(assessment).toContain(`alter table public.${t} enable row level security`)});
  it('protects correction sessions and preserves Result/Attempt RPC boundary',()=>{expect(rapid).toContain('alter table public.correction_sessions enable row level security');expect(assessment).toContain('revoke insert,update,delete on public.assessment_results, public.assessment_attempts from authenticated');expect(rapid).toContain('function public.apply_assessment_judgement_operation');expect(bulk).toContain('function public.apply_assessment_bulk_operation')});
  it('keeps explicit result states and attempt kinds',()=>{for(const state of['UNCHECKED','GRADED','MISSING','EXCUSED'])expect(assessment).toContain(`'${state}'`);for(const kind of['ORIGINAL','MAKEUP','REMEDIAL','CORRECTION'])expect(assessment).toContain(`'${kind}'`)});
  it('adds narrow continuity RPCs without browser workspace ownership input',()=>{expect(continuity).toContain('function public.start_teaching_meeting_operation');expect(continuity).toContain('function public.apply_meeting_checkpoint_operation');expect(continuity).toContain('function public.set_teaching_meeting_status_operation');expect(continuity).toContain('auth.uid()');expect(continuity).not.toContain('p_workspace_id')});
  it('narrows direct Meeting/Checkpoint mutations without weakening RLS or unrelated Teaching Core grants',()=>{expect(writeBoundary).toContain('revoke insert, update, delete on table public.meetings from authenticated');expect(writeBoundary).toContain('revoke insert, update, delete on table public.checkpoints from authenticated');expect(writeBoundary).toContain('grant select on table public.meetings to authenticated');expect(writeBoundary).toContain('grant select on table public.checkpoints to authenticated');expect(writeBoundary).not.toContain('public.materials');expect(writeBoundary).not.toContain('public.activities')});
  it('adds append-only re-entry baseline ownership and bounded Today RPCs',()=>{expect(today).toContain('alter table public.continuity_baselines enable row level security');expect(today).toContain('grant select on public.continuity_baselines to authenticated');expect(today).not.toContain('grant insert on public.continuity_baselines to authenticated');expect(today).toContain('function public.read_today_class_contexts()');expect(today).toContain('function public.read_today_active_correction()');expect(today).toContain('function public.record_continuity_baseline_operation');expect(today).toContain('limit 24')});
  it('protects pacing data behind owned revision-checked RPC writes',()=>{expect(pacing).toContain('alter table public.lesson_pacing_plans enable row level security');expect(pacing).toContain('revoke insert,update,delete on public.lesson_pacing_plans from authenticated');expect(pacing).toContain('function public.upsert_lesson_pacing_plan_operation');expect(pacing).toContain('auth.uid()');expect(pacing).not.toContain('p_workspace_id')});
  it('protects reporting snapshots, policies, cycles and audit history behind owned RPC writes',()=>{for(const table of['audit_events','reporting_policies','reporting_cycles','report_snapshots','report_snapshot_rows'])expect(reporting).toContain(`alter table public.${table} enable row level security`);expect(reporting).toContain('function public.calculate_report_snapshot_operation');expect(reporting).toContain('function public.reopen_reporting_cycle_operation');expect(reporting).toContain('auth.uid()');expect(reporting).not.toContain('p_workspace_id')});
  it('protects artifacts, append-only versions and private object metadata behind owned RPCs',()=>{for(const table of['artifacts','artifact_versions','artifact_objects'])expect(artifacts).toContain(`alter table public.${table} enable row level security`);for(const fn of['create_artifact_operation','append_artifact_version_operation','archive_artifact_operation','reserve_artifact_object_operation','confirm_artifact_object_operation'])expect(artifacts).toContain(`function public.${fn}`);expect(artifacts).toContain('auth.uid()');expect(artifacts).not.toContain('p_workspace_id');expect(artifactHardening).toContain('perform pg_advisory_xact_lock');expect(artifactHardening).toContain("ao.state in ('PENDING_UPLOAD','READY')");expect(artifactGovernor).toContain('revision=a.revision+1');expect(artifactGovernor).toContain("if art.status<>'active' then raise exception 'artifact archived'")});
  it('adds owned portable recovery RPCs without exposing workspace selection',()=>{expect(recovery).toContain('function public.export_portable_backup()');expect(recovery).toContain('function public.restore_portable_backup_operation');expect(recovery).toContain('auth.uid()');expect(recovery).not.toContain('p_workspace_id')});
});
