import{describe,expect,it}from'vitest';import{readFileSync}from'node:fs';
import type{PendingOperation}from'../../src/domain/safeWork';import type{AcademicClass,Checkpoint,Meeting}from'../../src/domain/academic';
import{classifyReentryAge,deriveTodayModel,latestLocalCheckpointForMeeting,type TodayClassContext,type TodayServerSnapshot}from'../../src/services/academic/today';
import{deriveClassContinuity,type TeachingCoreContext}from'../../src/services/academic/teachingCore';
const todayService=readFileSync('src/services/academic/today.ts','utf8'),todayUi=readFileSync('src/components/Today.tsx','utf8'),rapidUi=readFileSync('src/components/RapidCorrection.tsx','utf8'),app=readFileSync('src/app/App.tsx','utf8'),migration=readFileSync('supabase/migrations/202609060001_today_reentry.sql','utf8');
const now=new Date('2026-09-06T10:00:00+07:00');
function ctx(p:Partial<TodayClassContext>={}):TodayClassContext{return{class_id:'C1',class_name:'VIII A',active_meeting_id:null,active_meeting_occurred_at:null,active_lesson_title:null,latest_actual_meeting_id:'M0',latest_actual_meeting_occurred_at:'2026-09-05T08:00:00Z',latest_actual_meeting_status:'completed',active_checkpoint_id:null,active_checkpoint_stopped_at:null,active_checkpoint_next_step:null,active_checkpoint_recorded_at:null,latest_checkpoint_id:'CP0',latest_checkpoint_meeting_id:'M0',latest_checkpoint_stopped_at:'Halaman 10',latest_checkpoint_next_step:'Nomor 2',latest_checkpoint_recorded_at:'2026-09-05T08:30:00Z',latest_baseline_id:null,latest_baseline_kind:null,latest_baseline_stopped_at:null,latest_baseline_next_step:null,latest_baseline_recorded_at:null,effective_source:'checkpoint',effective_stopped_at:'Halaman 10',effective_next_step:'Nomor 2',effective_recorded_at:'2026-09-05T08:30:00Z',...p};}
function snapshot(classes:TodayClassContext[],correction:TodayServerSnapshot['correction']=null):TodayServerSnapshot{return{classes,correction};}
function op(status:PendingOperation['status'],meetingId='M1',createdAt='2026-09-06T01:00:00Z',stoppedAt='x'):PendingOperation{return{op_id:`OP-${status}-${createdAt}`,auth_user_id:'U',workspace_id:'W',entity_type:'meeting_checkpoint',entity_id:meetingId,causal_key:`meeting_checkpoint:${meetingId}`,operation_kind:'meeting.checkpoint',payload:{meeting_id:meetingId,stopped_at:stoppedAt,next_step:null},created_at:createdAt,attempt_count:0,last_attempt_at:null,status,expected_revision:0,last_error_code:null,conflict_snapshot:null};}

describe('R3.4-02 Today contracts',()=>{
 it('active Meeting outranks recent context',()=>{const model=deriveTodayModel(snapshot([ctx({class_id:'C1'}),ctx({class_id:'C2',class_name:'VIII B',active_meeting_id:'M2',active_meeting_occurred_at:'2026-09-06T02:00:00Z'})]),[],now);expect(model.primary).toEqual({kind:'continue-class',classId:'C2',label:'CONTINUE CLASS'});});
 it('latest meaningful checkpoint survives an active Meeting boundary',()=>{const classroom={id:'C',workspace_id:'W',academic_period_id:'P',identity_key:'c',display_name:'C',status:'active'} as AcademicClass;const old={id:'M-old',workspace_id:'W',class_id:'C',lesson_id:null,lesson_version_id:null,occurred_at:'2026-09-05T08:00:00Z',status:'completed'} as Meeting;const active={...old,id:'M-new',occurred_at:'2026-09-06T08:00:00Z',status:'in_progress'} as Meeting;const checkpoint={id:'CP',workspace_id:'W',meeting_id:'M-old',sequence_no:1,stopped_at:'Old LAST',next_step:'Old NEXT',recorded_at:'2026-09-05T09:00:00Z'} as Checkpoint;const core={materials:[],lessons:[],lessonVersions:[],meetings:[old,active],checkpoints:[checkpoint],activities:[],activityMeetings:[]} as TeachingCoreContext;const derived=deriveClassContinuity([classroom],core)[0];expect(derived.activeMeeting?.id).toBe('M-new');expect(derived.latestMeaningfulCheckpoint?.id).toBe('CP');expect(derived.effectiveContext?.stopped_at).toBe('Old LAST');});
 it('active CorrectionSession is resumable work but never academic Attempt evidence',()=>{const correction={session_id:'S',assessment_id:'A',assessment_title:'Quiz',class_id:'C',class_name:'IX A',current_enrollment_id:'E',started_at:'2026-09-06T01:00:00Z',updated_at:'2026-09-06T02:00:00Z',active_count:1};const model=deriveTodayModel(snapshot([],correction),[],now);expect(model.primary).toEqual({kind:'resume-correction',assessmentId:'A',label:'RESUME CORRECTION'});expect(todayService).not.toContain('AttemptKind');expect(migration).not.toContain('assessment_attempts');});
 it('Rapid Correction restores only a valid active cursor once per Assessment',()=>{expect(rapidUi).toContain("cursorInitializedAssessment.current!==assessmentId");expect(rapidUi).toContain("next.session?.status==='active'?next.session.current_enrollment_id:null");expect(rapidUi).toContain("next.enrollments.some(enrollment=>enrollment.id===cursor)?cursor:''");expect((rapidUi.match(/setSelected\(cursor&&/g)??[])).toHaveLength(1);});
 it('Pending Safe is attention and is never labelled Saved',()=>{const model=deriveTodayModel(snapshot([]),[op('PENDING_SAFE')],now);expect(model.beforeLeaving[0].detail).toContain('Pending Safe');expect(model.beforeLeaving[0].detail).not.toContain('Saved');});
 it('no-work state is honest and Safe Work attention makes empty false',()=>{expect(deriveTodayModel(snapshot([]),[],now)).toMatchObject({primary:null,empty:true});expect(deriveTodayModel(snapshot([]),[op('FAILED')],now)).toMatchObject({primary:null,empty:false});expect(todayUi).toContain("model.empty?");expect(todayUi).toContain('Tidak ada pekerjaan utama di NOW');expect(todayUi).toContain("state.status==='error'");expect(todayUi).toContain('Ini bukan berarti tidak ada pekerjaan');});
 it('latest local checkpoint is exact-Meeting scoped and deterministic newest whole fact',()=>{const old=op('FAILED','M1','2026-09-06T01:00:00Z','old'),newest=op('CONFLICT','M1','2026-09-06T02:00:00Z','newest'),wrong=op('PENDING_SAFE','M0','2026-09-06T03:00:00Z','wrong');expect((latestLocalCheckpointForMeeting([newest,wrong,old],'M1')?.payload as any).stopped_at).toBe('newest');expect(latestLocalCheckpointForMeeting([wrong],'M1')).toBeNull();});
 it('recovery uses exact meetings RLS lookup and never bounded-row guessing',()=>{expect(todayService).toContain("client.from('meetings').select('class_id')");expect(todayUi).toContain('Class untuk checkpoint ini belum dapat ditentukan.');expect(todayUi).not.toContain('onOpenContinuity(context?.class_id)');});
 it('stale context gets re-entry while recent context does not',()=>{const stale=ctx({effective_recorded_at:'2026-08-20T08:00:00Z'}),recent=ctx({effective_recorded_at:'2026-09-01T08:00:00Z'});expect(classifyReentryAge(stale.effective_recorded_at,now)).toBe('stale');expect(deriveTodayModel(snapshot([stale]),[],now).primary?.kind).toBe('quick-update');expect(classifyReentryAge(recent.effective_recorded_at,now)).toBe('recent');expect(deriveTodayModel(snapshot([recent]),[],now).primary?.kind).toBe('start-class');});
 it('active Meeting suppresses stale re-entry action rendering',()=>{expect(todayUi).toContain("age==='stale'&&!context.active_meeting_id");});
 it('Start From Today is append-only and preserves historical state',()=>{expect(migration).toContain("'START_FROM_TODAY'");expect(migration).toContain('insert into public.continuity_baselines');expect(migration).not.toMatch(/delete\s+from\s+public\.(meetings|checkpoints|correction_sessions)/i);expect(migration).not.toMatch(/update\s+public\.(meetings|checkpoints|correction_sessions)/i);});
 it('dispatcher read boundary is bounded and never calls loadOwnedTeachingCore',()=>{expect(todayService).not.toContain('loadOwnedTeachingCore');expect(todayService).toContain("client.rpc('read_today_class_contexts')");expect(migration).toMatch(/read_today_class_contexts[\s\S]*limit 24/);expect(migration.match(/limit 1/g)?.length??0).toBeGreaterThanOrEqual(5);});
 it('Today is the default App home and direct targets are forwarded',()=>{expect(app).toContain("useState<WorkspaceMode>('today')");expect(app).toMatch(/<TeachingContinuity[^>]*initialClassId=\{continuityTarget\}/);expect(app).toMatch(/<RapidCorrection[^>]*initialAssessmentId=\{rapidTarget\}/);});
 it('stale rule is calendar-week based rather than an hour timer',()=>{expect(todayService).toContain('previous local calendar week');expect(todayService).not.toContain('72');});
});
